### ISSUE TITLE
App failed to save

### ISSUE THREAD

**Issue by Romasa** [aukgit/WeReviewProject#122]
1. Click on the Post App
2. Enter all required information

![image](https://cloud.githubusercontent.com/assets/3047801/16919673/7ecdcd52-4d2c-11e6-816e-2b0c02c5f81d.png)

Prob # 1: No particular message is given as why posting app is failed
Prob # 2: The files I have uploaded are not visible, removed or what can't say

PS: I tried to submit a video file in the youtube cover file of 1.5 MB size and there was a cursor as if it is trying to upload that file and it keep on showing that icon until I clicked the button again to enter an image file. After submitting on click button I received that error.

**Comment by aukgit** [comment]
![image](https://cloud.githubusercontent.com/assets/4561204/16986648/92cf0112-4ea9-11e6-80e3-34eb35711c89.png)
3dc1c1184eccdf553e7d339eb2eca671dc79030d
7b3e065fa8af4b3db176f40102ac5e2a8d7c87a5
6b86c8d5e0aae832edda9de2f74936c632497438
8e2e0e9dc6e43fb764cd3700f3c5c6ed24e46ac3
