### ISSUE TITLE
Error Message font size too small

### ISSUE THREAD

**Issue by Romasa** [aukgit/WeReviewProject#81]
1. From Homepage, click on Login -> Register
2. Fill in the form using existing username. 
3. Click on the Register button.
4. Following error message will be received with too small font size. Font size should be increased.
   ![image](https://cloud.githubusercontent.com/assets/3047801/14490172/2ae02828-0193-11e6-8408-435528e46c1c.png)

**Comment by aukgit** [comment]
This bug will not be fixed. Since small font size is a web design concept

If you can read it then others can as well, That's the purpose of it.
We also think of the mobile screen sizes as well
