### ISSUE TITLE
Necessary fields should be indicated

### ISSUE THREAD

**Issue by Romasa** [aukgit/WeReviewProject#87]
1. After login click on Post App
2. Fill in the necessary items marked with red star 
3. Click on "I agree" check and then click on Create Button
4. Following error will generate
   ![image](https://cloud.githubusercontent.com/assets/3047801/14749246/3680eefc-08e0-11e6-8667-ad41384b901e.png)

**Comment by aukgit** [comment]
https://github.com/aukgit/WeReviewProject/commit/1a96929e85f530eece0f15f3644788ad415dbad2
