### ISSUE TITLE
Firefox not showing Logged in User Options

### ISSUE THREAD

**Issue by Romasa** [aukgit/WeReviewProject#95]
1. Login from the homepage using any user
2. Now hover the mouse over the User name. It should show options like logout, manage etc, which firefox is not showing, in chrome it is working ok. PS: I have installed firefox afresh
   ![image](https://cloud.githubusercontent.com/assets/3047801/15206385/8fed6848-1840-11e6-85f4-04dcb01d751e.png)

**Comment by aukgit** [comment]
Issue doesn't persist.
