### ISSUE TITLE
Dual sessions in the same browsers

### ISSUE THREAD

**Issue by Romasa** [aukgit/WeReviewProject#96]
I visited wereviewapp.com, tried to login with id its.romi@gmail.com and happened to forgot my password and then tried to reset my password which gave me 500 error. Then:
1. I refreshed the home page and found its.romi@gmail.com already logged in.
2. When I hover over the username then I faced issue # 95
![image](https://cloud.githubusercontent.com/assets/3047801/15211688/8716e0f0-185e-11e6-86e8-8de0516e12a5.png)
The above picture shows me logged in as Romasa i.e., its.romi@gmail.com
3. Clicking on username navigates to manage account page and there I found mau.masud@gmail.com  logged in.
![image](https://cloud.githubusercontent.com/assets/3047801/15211726/cdb40704-185e-11e6-8594-3ad617a277c2.png)

I considered it as a temporary mistake, reinstalled firefox and chrome both, shut down and then turn laptop on again and repeated the procedure and same thing happened again.

Considering myself logged in with mau.masud@gmail.com, I clicked on Post App button to try to post an app it took me to the login page and now no user is logged in.

![image](https://cloud.githubusercontent.com/assets/3047801/15211833/641377f2-185f-11e6-86eb-63b68af8d424.png)

**Comment by aukgit** [comment]
Issue doesn't persist
